[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/auth/status"
  to = "/.netlify/functions/auth-status"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/login"
  to = "/.netlify/functions/auth-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/logout"
  to = "/.netlify/functions/auth-logout"
  status = 200
  force = true

[[redirects]]
  from = "/api/miniloto/csv"
  to = "/.netlify/functions/miniloto-csv"
  status = 200
  force = true
